## Artifact orchestration wrapper (directories + shared facts + includes + summary)
- name: Ensure required directories exist on lp
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  loop:
    - { path: "/tmp", mode: "0777" }
    - { path: "/opt", mode: "0755" }
  tags: [artifacts]

- name: Set image URLs and paths dynamically
  set_fact:
    saiserver_url: "{{ artifactory_base_url }}/{{ build_release }}/{{ saiserver_image_name }}"
    imc_config_url: "{{ artifactory_base_url }}/{{ build_release }}/{{ imc_config_image_name }}"
    debug_cli_url: "{{ artifactory_base_url }}/{{ build_release }}/{{ debug_cli_image_name }}"
    saiserver_lp: "/tmp/saiserver.tgz"
    imc_config_lp: "/tmp/imc-config.tgz"
    debug_cli_lp: "/opt/debug-cli.tgz"
  tags: [artifacts]

- name: Acquire saiserver artifact
  import_tasks: artifacts/saiserver.yml
  tags: [artifacts]

- name: Acquire imc-config artifact
  import_tasks: artifacts/imc_config.yml
  tags: [artifacts]

- name: Acquire debug-cli artifact
  import_tasks: artifacts/debug_cli.yml
  tags: [artifacts]

- name: LP deployment summary
  debug:
    msg:
      - "debug-cli tarball placed at {{ debug_cli_lp }}"
      - "debug-cli extracted into /opt (changed={{ debug_cli_extract.changed or debug_cli_download.changed }})"
      - "Final path expectation: /opt/debug-cli"
      - >-
        {{ 'saiserver provided locally from ' + _local_saiserver_abs if (local_saiserver_tarball_path | length > 0) else 'saiserver downloaded from ' + saiserver_url }}
      - >-
        {{ 'saiserver download changed=' + (saiserver_download.changed | default(false) | string) if (local_saiserver_tarball_path | length == 0) else 'local copy assumed changed=true' }}
      - >-
        {{ 'imc-config provided locally from ' + _local_imc_config_abs if (local_imc_config_tarball_path | default('') | length > 0) else 'imc-config downloaded from ' + imc_config_url }}
      - >-
        {{ 'debug-cli provided locally from ' + _local_debug_cli_abs if (local_debug_cli_tarball_path | default('') | length > 0) else 'debug-cli downloaded from ' + debug_cli_url }}
  tags: [artifacts]
