# ACC availability, key registration and health verification
- name: Wait for ACC SSH reachability from IMC (retry)
  shell: >-
    ssh -o BatchMode=yes -o ConnectTimeout=5 -o StrictHostKeyChecking=no
    root@{{ hostvars['acc']['ansible_host'] }} 'echo ACC_UP'
  register: acc_reach
  delegate_to: imc
  retries: 60   # 60 * 10s = 600s max
  delay: 10
  until: acc_reach.rc == 0
  changed_when: false
  failed_when: false

- name: Capture ACC ed25519 host key from IMC (retry)
  command: ssh-keyscan -t ed25519 {{ hostvars['acc']['ansible_host'] }}
  register: acc_keyscan
  delegate_to: imc
  retries: 8
  delay: 5
  until: acc_keyscan.rc == 0 and acc_keyscan.stdout != ''
  changed_when: false
  failed_when: false

- name: Register ACC host key on IMC
  known_hosts:
    name: "{{ hostvars['acc']['ansible_host'] }}"
    key: "{{ (acc_keyscan.stdout_lines | select('match','^.*ssh-ed25519.*') | list | first) | default('') }}"
    state: present
  delegate_to: imc
  when: acc_keyscan.rc == 0 and acc_keyscan.stdout != ''

- name: Verify ACC basic health via IMC SSH
  shell: >-
    ssh -o BatchMode=yes -o ConnectTimeout=5 -o StrictHostKeyChecking=no
    root@{{ hostvars['acc']['ansible_host'] }} 'echo ACC_HEALTH_OK'
  register: acc_health_imc
  delegate_to: imc
  changed_when: false
  retries: 5
  delay: 6
  until: acc_health_imc.rc == 0

- name: ACC health summary
  debug:
    msg:
      - "ACC IMC SSH health rc={{ acc_health_imc.rc }}"