- name: Bootstrap SSH trust chain
  hosts: localhost
  gather_facts: no
  vars:
    reset_known_hosts: true
    lp_host: "{{ hostvars['lp']['ansible_host'] }}"
    lp_user: "{{ hostvars['lp']['ansible_user'] | default('root') }}"
    imc_host: "{{ hostvars['imc']['ansible_host'] }}"
    imc_user: "{{ hostvars['imc']['ansible_user'] | default('root') }}"
    acc_host: "{{ hostvars['acc']['ansible_host'] }}"
    acc_user: "{{ hostvars['acc']['ansible_user'] | default('root') }}"
  tasks:
    - import_tasks: tasks/01_bootstrap_ssh.yml

- name: Host driver cleanup
  hosts: host
  gather_facts: no
  tasks:
    - import_tasks: tasks/02_stop_driver.yml

- name: Download images on lp
  hosts: lp
  vars_files:
    - "../group_vars/vault.yml"
    - "../group_vars/all.yml"
  tasks:
    - import_tasks: tasks/03_download_images.yml

- name: Distribute images and reboot IMC
  hosts: imc
  tasks:
    - import_tasks: tasks/04_distribute_and_reboot.yml
    - name: ACC availability and key registration & health
      import_tasks: tasks/05_acc_health.yml
    - import_tasks: tasks/06_summary.yml

